### ISSUE TITLE
Declaration of ClassMetadataFactory::setEntityManager() is not compatible

### ISSUE THREAD

**Issue by Budry** [Kdyby/Doctrine#150]
Hi,
when I use
```json
"require": {
    "kdyby/doctrine": "@dev"
}
"minimum-stability": "dev"
```
I'm getting error `Declaration of Kdyby\Doctrine\Mapping\ClassMetadataFactory::setEntityManager() should be compatible with Doctrine\ORM\Mapping\ClassMetadataFactory::setEntityManager(Doctrine\ORM\EntityManagerInterface $em)`

Problematic commit https://github.com/doctrine/doctrine2/commit/e65417f1f618c47f8df6abf235ffc5c075d34702

**Comment by fprochazka** [comment]
Solved in master.
