### ISSUE TITLE
Wrong use in NativeQueryBuilder

### ISSUE THREAD

**Issue by freaz** [Kdyby/Doctrine#159]
In NativeQueryBuilder is naming collision with class and Doctrine original class.

https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/NativeQueryBuilder.php#L14

**Comment by enumag** [comment]
You mean that the name [here](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/NativeQueryBuilder.php#L40) should not be fully qualified? Can you send a PR?

**Comment by freaz** [comment]
In Kdyby\Doctrine namespace is QueryBuilder. So there must be alias or fully qualified name for it.

**Comment by enumag** [comment]
@faaz Right but you need to fix this line as well ;-) https://github.com/freaz/Doctrine/blob/de04b4662401700d358288cc54baa6de0d827d10/src/Kdyby/Doctrine/NativeQueryBuilder.php#L156

**Comment by freaz** [comment]
I saw that, but should it be Doctrines or Kdybys?

Because this looks as accidentally added import and also addSelect is overrided Doctrine's QueryBuilder method. So I thought that it should be Kdybys class.

**Comment by enumag** [comment]
@freaz Doctrines. Kdybys QueryBuilder doesn't have getSQL method.

**Comment by freaz** [comment]
Yeah right. Sorry
