### ISSUE TITLE
Custom types not loaded properly in console commands

### ISSUE THREAD

**Issue by freaz** [Kdyby/Doctrine#161]
Only in 2.3.0

I am not able to determine why, but I see some changes how custom types are handled.

It seems, that in application they work. But if I run orm:schema-tools:*, console throws Unknown database type.

**Comment by matej21** [comment]
See #158

**Comment by enumag** [comment]
@freaz #158 is merged, try it and close this if it works.

**Comment by freaz** [comment]
Looks good.
