### ISSUE TITLE
Nested transactions with nested flush

### ISSUE THREAD

**Issue by urugator** [Kdyby/Doctrine#172]
Doctrine supports nesting transactions, so you can easily use your atomic methods in one anoter and keep whole operation atomic (the actual commit happens with the outermost commit). Unfortunatelly there is no way to somehow postpone flushing in nested transactions. This potentionally leads to uneccessary number of database hits. It might be nice to be able to control flushing like transactions:

$em->beginFlushing() // increments nesting counter
$em->flush() // works the same way as before
$em->nestedFlush() // decrements nesting counter and calls $em->flush() if counter is on zero or throws an exception if beginFlushing() was not called before

And also provide a version of EntityManager::transactional() using this type of flushing instead of normal one.
What do you think?

**Comment by fprochazka** [comment]
If this were to be implemented, it has to be done on the UnitOfWork level, which means Kdyby/Doctrine has basically no way of doing it. You might wanna start a discussion in [Doctrine2 issue tracker](http://www.doctrine-project.org/jira/browse/DDC)

**Comment by urugator** [comment]
Nope, the implementation is actually pretty trivial and depends only on public EntityManager::flush method. So in fact the implementation does not have to reside in entity manager itself, but I think it would make sense to do so. 
Everbody can implement it within few minutes. I just want to be sure that it makes sense and I am not inventing some total crap. And I would prefer having this in Kdyby's EntityManager instead of inheriting it.

**Comment by urugator** [comment]
Ok, here is a quick untested prototype just to get the idea:
http://pastebin.com/6mS2H4Se

**Comment by fprochazka** [comment]
I think that's overcomplicated.
Still, you might wanna open issue in Doctrine2 issue tracker, maybe they'll have different opinion :)

**Comment by urugator** [comment]
I made a mistake in that prototype, you don't have to call nestedFlush (actually you can't, it would throw an exception) in that usage examples (updated).

Only thing which is changed from the Doctrine user's perspective in proposed solution is ability to decide:
Do I need an immediate flush? (for example to immediately retrieve new entity's ID). If yes, than I will call $em->flush(). (or use classic EntityManager::transactional() which flushes automatically)
Do I need to flush, but it might be possibly postponed by caller (actually most of the cases)? Then I don't have to do anything if I am using new transactional method (otherwise I can manually call beginFlushing() and nestedFlush() or possibly something like autoNestedFlush($func) ).

There are only two other solutions to this problem:
1) Don't reuse DAO methods (not really a solution).
2) Create more versions for each of your DAO method:  One, non flushing, which can be reused inside your DAO layer (you might need it to be public, but not part of your DAO layer API) and another one, flushing, as part of DAO layer API. When reusing reused method, you will end up with even more non-flushing versions of your methods.
3) Add parameter $flush to each DAO method (in this case you can't use EntityManager::transactional() because it flushes automatically)
That's overcomplicated in my opinion .

**Comment by fprochazka** [comment]
There are already too many things in this library, that should be solved by Doctrine itself, not Kdyby. It is simply not a prirority for me to send those pullrequest and lobby those features in. 

I thank you for your effort, but please do not waste any more energy on this in this repository, I don't think it should be part of Kdyby. Create issue in Doctrine 2 issue tracker and go from there.

**Comment by urugator** [comment]
No problem. I have maybe rather needed to hear that it's not complete nonsence, than necessarily having this "feature" as part of Kdyby. Possible interest could imply that it isn't or that someone has been solving similar problem. I also believe that it's faster and easier to carry though such possible enhancements in smaller projects like this (more agile, shorter release cycles, often works as "playgrounds" for the larger ones...), that's why I went here first. My apoligies for offtopic, Howgh :)

**Comment by fprochazka** [comment]
It's no offtopic, I'm glad you're interested. I can understand now what this is good for but I don't have this problem so I'm not sure I'd be willing to add another such big architectural opinion into Kdyby. I've made that in past and it didn't end up well (DAO might be a good example). As this is an architectural tool that basically everyone would adopt, I'd have to **really need it** to be able to accept it and stand behind it beeing in Kdyby.

If you open the issue, past the link here please. I'd be interested to watch the discussion. Thank you :)
