### ISSUE TITLE
Autogenerated parameter name

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Doctrine#177]
Sometimes you don't wanna think about how are you naming your parameter and just wanna prevent potencial conflits when building a complex query.

``` php
->andWhere('a.foo = :one')->setParameter('one', 1)
// a lot of code
->andWhere('a.bar = :one')->setParameter('one', 2)
// this overwrites the first value
```

The solution would be something like

``` php
->andWhere('a.foo = ?', 1) // name $query->parameters->count() + 1
// a lot of code
->andWhere('a.bar = ?', 2) // name $query->parameters->count() + 1
```

This ofcourse means you're giving up overwriting the parameter, since you don't know what it would be named.
- [ ] consider sending a pullrq to doctrine directly

**Comment by urugator** [comment]
This would break the existing QueryBuilder API, since where()/andWhere() already accepts multiple arguments - all representing predicates.
Adding new methods to provide this feature could be a better idea.
Also, I think that following variants should be supported as well
```
->whereWithValues('a.foo = ?1 AND a.bar = ?2', array(1, 2))
->whereWithValues('a.foo = :one AND a.bar = :two', array('one' => 1, 'two' => 2))
```
Btw setting parameters this way is possible in Doctrine1

**Comment by fprochazka** [comment]
> This would break the existing QueryBuilder API

I fail to see why it should.

**Comment by urugator** [comment]
Currently, it's possible to call this:
```
qb->andWhere('a.foo = ?1', 'b.foo = ?2', 'c.foo = ?3')
```
How do you intend to distinguish that the second (or possibly last) method's argument is parameter's value and not another predicate?

**Comment by fprochazka** [comment]
Dibi does it and I've also implemented it :)  You can already do this with Kdyby/Doctrine

```php
->andWhere('a.foo = :one', 1)
```

**Comment by fprochazka** [comment]
But now that I think about it, I really might have to change it... :-/

**Comment by urugator** [comment]
Oh, I didn't know that... so you have already broke that API, because
```
->andWhere('a.foo = :one', 'a.bar = :two')
```
results in query with single predicate with parameter named "one" having value "a.bar = :two"
instead of two predicates with params named "one" and "two"
I am I right?

**Comment by fprochazka** [comment]
You're right. But I'm pretty sure that when I was implementing it, doctrine didn't know this :)

**Comment by fprochazka** [comment]
Fuck, I overlooked it. Well, at least I know how to fix it without BC Break. Will do ASAP.

**Comment by urugator** [comment]
Seems like it's there from the beggining, see method where() in
https://github.com/doctrine/doctrine2/blob/2.0.x/lib/Doctrine/ORM/QueryBuilder.php#L70

select, having, groupBy works similary

**Comment by fprochazka** [comment]
@urugator I think I've solved the problem :) https://github.com/Kdyby/Doctrine/commit/b25f2b50ef7a73bbe308c92444fc7f5501137d7c

**Comment by urugator** [comment]
So you have to change configuration to maintain BC...

Do you plan to provide inline params feature in fixed QueryBuilder by adding new methods (really not sure how they should be named)?

I have a question unrelated to this issue ... is it possible to somehow programatically modify the doctrines configuration before it's applied? By registering an event listener or something like that?

**Comment by fprochazka** [comment]
@urugator I think adding a line to config is smaller problem than finding all usages of inline params in your app. Also, new "big" version will be released shortly, so I can affort a few smaller BC Breaks.

No, since I don't know how would I name them.

---

Why are you then asking it here? Isn't forum better? Or new issue? 
Also, I don't understand what you mean by configuration and applying.

**Comment by urugator** [comment]
It's ok, I wasn't meant to criticize, but to clarify - for me and possible readers.

I didn't realize there is a Kdyby forum, it was quite late :) My apologies.
https://help.kdyby.org/question/?questionId=592

**Comment by fprochazka** [comment]
@urugator fair enough :) but I was hoping the commit message would clarify https://github.com/Kdyby/Doctrine/commit/b25f2b50ef7a73bbe308c92444fc7f5501137d7c, does it not?

**Comment by urugator** [comment]
Well, to me, the message sounds more like "change the config to gain the feature", but I think it should be more like "change the config to don't loose BC and maintain the feature", to emphasize that you actually have to change something in your code to remain BC, when you update to newer version.
I had to ensure which QueryBuilder is the default one by looking at code. 
Also as I am looking at it for a second time, the statement:
"you loose the ability to write multiple conditions in the QB"
is not entirely right, since you can still write multiple conditions, but with different syntax, but I admin it's a nitpicking.

**Comment by fprochazka** [comment]
Out of scope.
