### ISSUE TITLE
findByOne a ManyToMany asociace

### ISSUE THREAD

**Issue by jasin755** [Kdyby/Doctrine#182]
Pokud mám v entitě asociaci ManyToMany (pojmenujeme ji např. image_groups) a pokusím se udělat:

```
$this->entity_manager->getRepository('Entity')->findOneBy(array('width' => 100, 'height' => 100,  'image_groups' => $image_group));
```

Tak to spadně na SQL erroru: 

```
An exception occurred while executing 'SELECT t0.id_image_size AS id_image_size_1, t0.width AS width_2, t0.height AS height_3, t0.cutted AS cutted_4, t0.type AS type_5, t0.unused AS unused_6, t0.id_shop AS id_shop_7 
FROM image_sizes t0 WHERE t0.width = ? AND t0.height = ? AND t0.cutted = ? AND image_groups.id_image_size_group = ? LIMIT 1' 
with params [100, 100, 0, 3]:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "image_groups"
LINE 1: ...th = $1 AND t0.height = $2 AND t0.cutted = $3 AND image_grou...
                                                             ^
```

**Comment by fprochazka** [comment]
Ta logika co použije DQL ve `find*By` metodách hledá jestli jsou ve fieldech použity tečky a když ano, tak sama joinuje a builduje podmínky chytřeji. Kdybych tam měl cokoliv chytřejšího, tak by to bylo zbytečně pomalé, ale nechtěl jsem úplně odříznout původní metody, o kterých si myslím že jsou o maličko rychlejší.

Sice jsem tomu dal label bug, ale nejsem si úplně jistej jestli to za něj opravdu považovat.

Zkus tohle:

```php
$this->entityManager->getRepository('Entity')->findOneBy(array('width' => 100, 'height' => 100,  'imageGroups.id' => $image_group));
```

**Comment by fprochazka** [comment]
Ve `v4.0` bych mohl nějak čistěji oddělit magii na skladani find dotazů a původní chování.
