### ISSUE TITLE
Annotations cache invalidation when updating

### ISSUE THREAD

**Issue by mrtnzlml** [Kdyby/Doctrine#185]
[There is problem](https://help.kdyby.org/question/?questionId=439) with cache invalidation. It's related to the Doctrine library, but it's actually in Annotations. CacheCleaner is taking care of [almost all](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/Tools/CacheCleaner.php#L44-50) caches. Unfortunately if you add for example nullbale attribute to the entity annotation, Kdyby Doctrine doesn't invalidate (delete) annotation's cache:

```php
@ORM\Column(type="text")
```
```php
@ORM\Column(type="text", nullable=TRUE)
```

I am not sure if it's really issue, because it behaves correctly according to:

> The AnnotationReader works and caches under the assumption that all annotations of a doc-block are processed at once. That means that annotation classes that do not exist and aren’t loaded and cannot be autoloaded (using the AnnotationRegistry) would never be visible and not accessible if a cache is used unless the cache is cleared and the annotations requested again, this time with all annotations defined.

But I think, that in this special use case (when using `orm:schema-tool:update` command), Kdyby Doctrine should try to delete annotations cache. What do you think?

**Comment by fprochazka** [comment]
I see, this is indeed an issue!

**Comment by fprochazka** [comment]
Thank you for reporting. I believe this should be fixed now.
