### ISSUE TITLE
Make Kdyby\Console optional

### ISSUE THREAD

**Issue by Vrtak-CZ** [Kdyby/Doctrine#190]
Why Kdyby\Console is required? Why is not optional?

**Comment by fprochazka** [comment]
Doctrine is really hard to use without symfony console. I could make it optional, but what is the benefit? And is it worth it?

**Comment by TomasVotruba** [comment]
:+1: I personally turn of Kdyby\Console due to complicating dependencies on Nette\Application, Nette\Routing, Tracy etc. `Symfony\Console` is just fine.

**Comment by fprochazka** [comment]
@TomasVotruba you turn it off completely? Or just the hooking to application? I was considering adding some options to do that, but then I figured there is really no reason apart from some academical purity. Using console through Nette\Application has more pros than cons.

**Comment by TomasVotruba** [comment]
@fprochazka Completely. It's about redundant Nette dependencies, which makes hard to integrate other open-source packages. I respect "use what you need, don't use what you don't need."

**Comment by fprochazka** [comment]
I see.

**Comment by TomasVotruba** [comment]
@Vrtak-CZ I'm curious, what is your motivation?

**Comment by Vrtak-CZ** [comment]
I have lot's of applications without console. And I don't use schema from doctrine. So currently I don't need console.

Kdyby\Doctrine work's without console very well so why console is needed?

**Comment by fprochazka** [comment]
I don't really have any great arguments to not have it optional. So I'll do it.

**Comment by TomasVotruba** [comment]
> @Vrtak-CZ And I don't use schema from doctrine.

Could write some more or some example? E.g. I use enties + database schema.

**Comment by Majkl578** [comment]
:+1: Any unnecessary strong dependency is bad. ^^

@TomasVotruba: Some people may use different tools for schemas and migrations, e.g. Enterprise Architect and Phinx.

**Comment by castamir** [comment]
@Majkl578 I strongy recommend you NOT to use Phinx, because its full of nasty bugs (it suppress many exceptions and then it shows you that everything is OK even when most of migration weren't completly applied). It is also mainly focused on developing its custom database layer instead of migration tool itself, so when you hack Phinx to not use its default database layer, then you dont use 99% of its functionality...

**Comment by Majkl578** [comment]
@castamir Ok, cool, do not yell at me, I just mentioned some other known tools. :fearful:
