### ISSUE TITLE
Grab connection configuration from environment

### ISSUE THREAD

**Issue by srigi** [Kdyby/Doctrine#195]
Applications hosted on some kind of PaaS (Heroku) are usually configured not by files but by environment variables (for example `DATABASE_URL="pgsql://user:pass@localhost/dbname"`).

It would be nice to have bridge for this in `Kdyby/Doctrine`. Can you give me some hints, so I can try to implement this?
Thanks.

**Comment by Majkl578** [comment]
I think you can use something like:
```yml
foo: ::getenv(APP_DB_PASSWORD)
```
alternatively you can add the parameters in bootstrap via `$configurator->addParameters([...])`.

**Comment by fprochazka** [comment]
Simply create `config.php`

```php
if ($dbConfig = getenv('DATABASE_URL')) {
        // normalize $dbConfig

	return [
		'doctrine' => [
			'dbname' => $dbConfig['dbname'],
			'host' => $dbConfig['host'],
			'password' => $dbConfig['password'],
			// ...
		];
```

and include it in main config :)

**Comment by srigi** [comment]
Great, thanks. Even better than fiddling with DI extensions.
