### ISSUE TITLE
Custom orm:clear-cache

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Doctrine#196]
One command to rule them all, one command to find them, one command to bring them all and in the darkness.

http://forum.nette.org/cs/23853-kdyby-doctrine-nefunguje-table#p160157

**Comment by juniwalk** [comment]
Does this mean Doctrine CLI will clear Nette cache too? Not just Doctrine's?

**Comment by fprochazka** [comment]
No, just doctrine caches, but all of them. Command for cleaning cache of nette is in roadmap of https://github.com/Kdyby/Console/issues/7

**Comment by juniwalk** [comment]
Wow that is great! Thanks for info.

**Comment by fprochazka** [comment]
Note to self: symfony has some clean cache commands even for doctrine - look into it.

**Comment by fprochazka** [comment]
https://github.com/Kdyby/Doctrine/commit/c1951ee1c065f1f1ed680c37bd5fdb8d9273780d
