### ISSUE TITLE
Method safePersist() fails when using entity inheritance.

### ISSUE THREAD

**Issue by MartinStepar** [Kdyby/Doctrine#204]
I have abstract class Transaction and child class PayuTransaction. When persisting PayuTransaction with method safePersist(), Doctrine throws error about missing "inheritance" column: _Field 'orm_type' doesn't have a default value_ (orm_type is name of discriminator column).

**Comment by fprochazka** [comment]
I see. Can you send a pullrequest please?

**Comment by fprochazka** [comment]
This should be fixed since https://github.com/Kdyby/Doctrine/commit/74a1a9056a53e56544a4a4fbc85c95bf4ec38a4f
