### ISSUE TITLE
Nefunkčné ExtensionMethods

### ISSUE THREAD

**Issue by xrep** [Kdyby/Doctrine#209]
V aktuálnom Kdyby/Doctrine nefungujú ExtensionMethods (https://doc.nette.org/cs/2.3/php-language-enhancements#toc-rozsirujici-metody).
Ak použijem príklad vo vyššie uvedenej stránke pričom objekt zdedím z BaseEntity potom dostávam **Call to undefined method Closure::invokeArgs()**. Riešil som to tu: https://forum.nette.org/cs/24544-nefunkcny-extension-method#p163832

David mi poradil nahradiť **$cb->invokeArgs($args)** na riadku 194 za **call_user_func_array($cb, $args)** a ono to rieši problém :)

Bude toto pridané do ďalšej verzie prosím, resp. môžem nejako pomôcť s opravou?

**Comment by fprochazka** [comment]
Díky za report, v masteru by to mělo být opraveno https://github.com/Kdyby/Doctrine/commit/8df935c2d016b383358ef2ba764f73d09e876351
