### ISSUE TITLE
EntityRepository::countBy should return integer

### ISSUE THREAD

**Issue by richard-ejem** [Kdyby/Doctrine#211]
now it returns string (hydrated single scalar result). Returning int would be more natural / expected result of count* method, however it would be a minor BC break.

**Comment by fprochazka** [comment]
I agree it should return int and I don't consider it a big BC Break. @glubo promised to fix it sometime :P 

If you have the time @richard-ejem, It would be great if you could send a PR.

**Comment by richard-ejem** [comment]
Here you go #212 , it was quite easy fix :)
