### ISSUE TITLE
QueryObjects: Use EntityManager

### ISSUE THREAD

**Issue by juniwalk** [Kdyby/Doctrine#217]
Hi,
I've created library which is basically simpler implementation of your query objects, but it works with `EntityManager` instead of `EntityRepository`.

This is all good but this morning I had an idea, what if I implement `QueryExecutor` and `Queryable` in the `EntityManager` itself? It would need some work to unite argument API of the methods.

I wanted to ask on your opinion about this. I'd be more happier to have this directly in *Kdyby/Doctrine* instead of implementing it myself.

**Comment by fprochazka** [comment]
That might work.

**Comment by juniwalk** [comment]
Great! Thank you for the input. I will try PR for this but I might need some help if I get unsure about something.
