### ISSUE TITLE
How to get first result from ResultSet?

### ISSUE THREAD

**Issue by srigi** [Kdyby/Doctrine#223]
If I had this query:

```php
$resultSet = $repository->fetch($queryObject);
```

the `$resultSet` is an `IteratorAggregate` instance. How I can get the first result without using `foreach` construct?

**Comment by enumag** [comment]
```
$obj = $repository->fetchOne($queryObject);
```

**Comment by srigi** [comment]
Thanks, it works like a charm. It correctly returns one existing object or NULL if noting cannot be found. Behaviour that I need exactly.
