### ISSUE TITLE
Incorrect handling of association method names

### ISSUE THREAD

**Issue by lookyman** [Kdyby/Doctrine#227]
When I have a toMany association to an entity with name ending in 's' (e.g. Bus), I want to name it ending in 'es' (e.g. $buses). When I then try to call $entity->addBus($bus), I get an undefined method call exception.

**Comment by enumag** [comment]
I guess you're using `Kdyby\Doctrine\Entities\MagicAccessors`, right? It should be possible to fix it by adding some additional logic here: https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/Entities/MagicAccessors.php#L125-L191. Can you send a PR?

**Comment by lookyman** [comment]
That is exactly the part of the code I was talking about, yes. I can prepare a PR but it might take a while.

**Comment by lookyman** [comment]
Actually that didn't take any time at all.

**Comment by enumag** [comment]
Can you add some tests as well? https://github.com/Kdyby/Doctrine/blob/master/tests/KdybyTests/Doctrine/MagicAccesors.phpt

**Comment by lookyman** [comment]
Yep, I will. But THAT might take a while to get to, I don't have any more time right now.

Btw now that I think about it, isn't this a BC break?

**Comment by enumag** [comment]
Technically yes but someone would have to use a collection property like "buss" instead of "buses" for this change to break it.
