### ISSUE TITLE
Magix accessor is not working on php7

### ISSUE THREAD

**Issue by thaeriac** [Kdyby/Doctrine#229]
If I call for **$user->password** where user is instance of **App\Entities\UserEntity**.
It crash on **Cannot read an undeclared property App\Entities\UserEntity::$Password**

Solution is call **$user->getPassword()** but it is not ok too.

**Comment by thaeriac** [comment]
Sh*t. I have bad version of Kdyby\Doctrine.

Sry :(

**Comment by fprochazka** [comment]
No problem, glad you solved it :+1:
