### ISSUE TITLE
nette/di 2.3.8 broke repository as services registration

### ISSUE THREAD

**Issue by juniwalk** [Kdyby/Doctrine#234]
After updating nette/di to version 2.3.8, all repositories registered as services stop working as if the service was never registered. Downgrading to 2.3.7 temporarily fixes the problem.

Error message: `Service of type App\Entity\UserRepository used in @var annotation at App\Presenters\UserPresenter::$userRepository not found. Did you register it in configuration file?`

I was unable to find the place where the problem resides. We were discussing this on [twitter](https://twitter.com/juniwalk/status/689764597339914241).

**Comment by fprochazka** [comment]
Thanks for the report, I'll try to look into it asap.

**Comment by juniwalk** [comment]
I tried to find the problem but mu knowledge of nette/di and OrmExtension is really limited at best. Setting dependency on nette/di 2.3.7 was sufficient for now so no worries. :)

**Comment by fprochazka** [comment]
@juniwalk the tests have passed with https://github.com/nette/di/releases/tag/v2.3.8, I'm gonna have to come back to this tomorrow and investigate further :-/

**Comment by fprochazka** [comment]
![snimek obrazovky porizeny 2016-01-26 16 56 18](https://cloud.githubusercontent.com/assets/158625/12585766/be3bec98-c44d-11e5-8125-909bdfa84f5c.png)

**Comment by juniwalk** [comment]
Do you think it could be problem in my applications instead of kdyby/nette?

**Comment by fprochazka** [comment]
@juniwalk it's certainly possible :)

**Comment by juniwalk** [comment]
That would be bad, it happened in all my nette applications.

**Comment by fprochazka** [comment]
@juniwalk have you had a time to research it for a bit?

**Comment by juniwalk** [comment]
@fprochazka Hey, not really, but I have time now... I will look into it with fresh nette/web-project to eliminate possible my error. Gimme sec.

**Comment by juniwalk** [comment]
@fprochazka So I did fresh installation where I created really simple entity and repository.
```php
class HomepagePresenter extends Nette\Application\UI\Presenter
{
	/** @var \App\Entity\UserRepository @inject */
	public $userRepository;
}
```

This simple code Immediately breaks the code, strange thing is, that when I dump `$this->getContext();`, repository is in services list.

**Comment by juniwalk** [comment]
I guess the problem is in injecting, not registration itself, so it is probably in the nette/di itself, what do you think?

**Comment by juniwalk** [comment]
@fprochazka So I see I was right? The problem is in nette/di not in my code or kdyby/doctrine?

**Comment by MartinSadovy** [comment]
@juniwalk yes, it was bug in nette/di, https://github.com/nette/di/pull/95 this issue [closes #234]

**Comment by juniwalk** [comment]
Great, I installed nette/di:2.3.x-dev and it works again, I think we can close this.

**Comment by fprochazka** [comment]
:+1:
