### ISSUE TITLE
EntityRepository::countBy MSSql bug

### ISSUE THREAD

**Issue by josefzajac** [Kdyby/Doctrine#235]
Hi, 
I fount different result set from MySql vs MSSql, best explanation in examples

MySQL countBy query: 
```sql
SELECT COUNT(m0_.id) AS sclr_0 FROM mail_history m0_ LIMIT 1
```
returns 

```php
['sclr_0' => 19]
```

config [Doctrine Documentation here](http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/configuration.html#driver)
doctrine: driver: `sqlsrv`

MSSql countBy query:
```sql
WITH dctrn_cte AS (
    SELECT TOP 1 COUNT(m0_.id) AS sclr_0 FROM mail_history m0_) 
SELECT * FROM (
    SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 0)) AS doctrine_rownum 
FROM dctrn_cte) AS doctrine_tbl 
WHERE doctrine_rownum BETWEEN 1 AND 1 
ORDER BY doctrine_rownum ASC
```
returns 

```
['sclr_0' => 19, 'doctrine_rownum' =>1] 
```

but https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/EntityRepository.php#L81 expects SingleResult :(

**Comment by fprochazka** [comment]
@josefzajac so the query that one would expect to only return one column returns two in mssql? :-/

**Comment by josefzajac** [comment]
Yep,

**Comment by josefzajac** [comment]
Yep :/ mssql interpretation of count query is obviously complicated.
Maybe try search for similar issues or Doctrine implementations, I didn't found.

sql version:
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
Aug 19 2014 12:21:34 
Copyright (c) Microsoft Corporation
Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)
