### ISSUE TITLE
Independency on Kdyby/Events

### ISSUE THREAD

**Issue by enumag** [Kdyby/Doctrine#239]
I'd like to remove Kdyby/Events from my projects. The reason is that Kdyby/Events is overcomplicated and I'd prefer some minimalistic integration of Doctrine EventManager instead. I don't need Nette/Object integration, I don't actually need namespaces, I rarely need debug panel, and I don't even want priorities.

The only thing I really do need is subscribers as services which means I just need to copy-paste the [ContainerAwareEventManager](https://github.com/symfony/doctrine-bridge/blob/master/ContainerAwareEventManager.php) from Symfony and modify it for Nette\DI.

If I wanted to implement priorities I'd do it completely compile-time. Of course that would mean no priorities for non-service listeners but I don't mind.

What does it mean for Kdyby/Doctrine? Is a service of type `Doctrine\Common\EventManager` enough or does it actually require something specific to Kdyby/Events?

**Comment by fprochazka** [comment]
Those are some good todos to solve for kdyby/events ;)

Anyway, there is no direct dependency on kdyby/events that I'm aware of, apart from the namespaces.

So basically, the `OrmExtension` could look if the `EventsExtension` is registered in compiler
- if it is, create the `NamespacedEventManager` service and bind it
- if not, look for it with `getByType(EventManager)` and wire that instead
- otherwise throw with explanation

Makes sense?

**Comment by enumag** [comment]
Isn't the NamespacedEventManager created by Kdyby/Events?

**Comment by fprochazka** [comment]
@enumag yes, but the only dependency on it is in the extension itself AFAIK

**Comment by enumag** [comment]
Oh were right. Kdyby/Events does not create NamespacedEVM, only normal EVM. The NamespacedEVM service is created by OrmExtension.

In my opinion it would be better to always use `getByType(EventManager)` in OrmExtension and not create any evm service. Or is there some important reason to do so?

**Comment by fprochazka** [comment]
@enumag yes it's needed to create the service, kdyby/events dropped support for not-namespaced events, and doctrine emits by default only plain events.

**Comment by enumag** [comment]
@fprochazka Oh I see now. In that case whot you wrote is exactly right. :-)
