### ISSUE TITLE
Possibility to inherit from EntityManager for Presenter inject

### ISSUE THREAD

**Issue by foxycode** [Kdyby/Doctrine#240]
I'd like to have possibility to inherit from `EntityManager` and tell him which connection to use. Now I can inject only default `EntityManager`. When I want to use another, I am using:
```php
$container->getService('doctrine.<name>.entityManager');
```

It would be great to switch connection according inherited class name like this:
```php
# config.neon
doctrine:
    default:
        driver: pdo_mysql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
    deals:
        driver: pdo_pgsql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
```

```php
class DealsEntityManager extends \Kdyby\Doctrine\EntityManager
{
    /**
     * Optional, take name from class name by default.
     */
    protected function getConnectionName()
    {
        return 'deals';
    }
}
```
```php
class SomePresenter extends \Nette\Application\UI\Presenter
{
    /**
     * @var DealsEntityManager
     */
    public $dealsEntityManager
}
```

**Comment by fprochazka** [comment]
One solution is to inject `Registry` and fetch the manager from it.

----

The other solution si for your cusotm EM to inherit from `Doctrine\ORM\Decorator\EntityManagerDecorator`, and then

```yml
services:
    - DealsEntityManager(@doctrine.deals.entityManager)
```

bam, autowiring works :)

**Comment by foxycode** [comment]
Great, thanks :)

**Comment by foxycode** [comment]
@fprochazka You have your own `EntityManager` in `Kdyby\Doctrine`. Will it be compatible if I use `EntityManagerDecorator` directly from Doctrine?

**Comment by fprochazka** [comment]
@foxycode I don't see why it shouldn't, the only disadvantage is that you won't be able to use the added syntax sugar.

**Comment by foxycode** [comment]
Tak bohužel:
```php
Nette\DI\ServiceCreationException: Service 'doctrine.helper.entityManager': Multiple services of type Doctrine\ORM\EntityManagerInterface found: doctrine.default.entityManager, 250_App_Model_DealsEntityManager in /home/liquid/projects/ehub/portal/vendor/nette/di/src/DI/ContainerBuilder.php:579
```
```yml
services:
    - App\Model\DealsEntityManager(@doctrine.deals.entityManager)
```
```php
<?php

namespace App\Model;


class DealsEntityManager extends \Doctrine\ORM\Decorator\EntityManagerDecorator
{
}
```

**Comment by fprochazka** [comment]
I see. The helper should be rewritten to use Registry or something, so the commands can switch EM https://github.com/Kdyby/Doctrine/issues/242. That should solve this issue.

**Comment by fprochazka** [comment]
This should be a sufficient temporary solution https://github.com/Kdyby/Doctrine/commit/d45ae6eb7ad6761bfaaa8572080a2713aae7607e, can you please test it?

**Comment by fprochazka** [comment]
It would probably help, to write a test for having defined two managers and a custom `EntityManagerDecorator`, so this won't break in the future.
Do you think you could write such test?

**Comment by foxycode** [comment]
@fprochazka I look into it.

**Comment by foxycode** [comment]
@fprochazka I created PR with test. I wanted to fix problem right away, but it's not that simple. I think that `EntityManagerDecorator` which implements `EntityManagerInterface` in fact colides with default `EntityManager` which is autowired. I'm not sure if there is way how to register `EntityManagerDecorator` with autowiring.

**Comment by fprochazka** [comment]
> Also, I reather woudn't use Registry in helpers. They are immutable this way and Symfony uses them this way too. Switching should be handled by creating new helper instance.

To be honest, I didn't look how symfony handles it, I just assumed. Creating new helper instance sounds better :+1:

**Comment by fprochazka** [comment]
It should work now https://github.com/Kdyby/Doctrine/commit/607fefa182faebef6755a1a509200e9ecada6213, let me know please, if there are any more problems.

**Comment by foxycode** [comment]
@fprochazka Works in my application and it even didn't break PR #247 which is great :smile: 

Thanks
