### ISSUE TITLE
Switching EM in console option like Symfony's DoctrineBundle has

### ISSUE THREAD

**Issue by foxycode** [Kdyby/Doctrine#242]
I don't know if it's Doctrine or Kdyby issue. I'd like to have separate entities for each connection so I be able to use console commands like `orm:schema-tool:create` for each database independently.

**Comment by fprochazka** [comment]
There is no mechanism to switch the manager in cli commands by default. In symfony, it is added in custom commands. Defining metadata per entity should be already possible. 

If you wanna help with this (that would be awesome!) look at symfony's `DoctrineBundle`, they have it solved pretty nicely.

**Comment by foxycode** [comment]
@fprochazka So if I update commands by creating console switch you merge it?

**Comment by fprochazka** [comment]
@foxycode yes, It's a real problem and I want it solved :)

**Comment by foxycode** [comment]
@fprochazka I wanted to start with creating current command tests. But when I run command test, it doesn't find `em` command helper. It is called in AbstractCommand: https://git.io/vaUM1
Even if it should be registered: https://git.io/vaUDf

My test code:
```php
<?php

namespace KdybyTests\Doctrine\Console;

use Kdyby\Doctrine\Console\SchemaCreateCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;
use Tester;
use Tester\Assert;

require_once __DIR__ . '/../../bootstrap.php';



class SchemaCreateCommandTest extends Tester\TestCase
{

    public function testCommand()
    {
        $application = new Application();
        $application->add(new SchemaCreateCommand);

        $command = $application->find('orm:schema-tool:create');
        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command'    => $command->getName(),
            '--dump-sql' => TRUE,
        ]);

        echo $commandTester->getDisplay();
    }

}

\run(new SchemaCreateCommandTest());
```

Can you please look into it?

**Comment by foxycode** [comment]
Relevant PR is #247

**Comment by fprochazka** [comment]
Solved.
