### ISSUE TITLE
Doctrine ~2.3 is dependant on Console ~2.3, which installs 2.5 with a BC break

### ISSUE THREAD

**Issue by Aurielle** [Kdyby/Doctrine#252]
I have an older project using Kdyby/Doctrine ~2.3 and I noticed that during `composer update` Kdyby/Console 2.5 gets installed. Console 2.5 includes a BC break (implemented default `--debug-mode` option), and this breaks all console commands from Doctrine. To solve this problem, I have to manually restrict Kdyby/Console to ~2.4 in my composer.json to ensure working console commands.

**Comment by Aurielle** [comment]
What about editing the release information or readme to at least warn about this?

**Comment by enumag** [comment]
We can't really edit readme of already released version either. And putting it to readme of the master branch doesn't feel right. We surely can update the release notes though. :+1:

**Comment by fprochazka** [comment]
I don't know how to solve this without force pushing tags.
