### ISSUE TITLE
Unnecessary MagicAccessors::__construct

### ISSUE THREAD

**Issue by hranicka** [Kdyby/Doctrine#254]
I have a problem with [MagicAccessors Trait](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/Entities/MagicAccessors.php#L42).

There is `__construct` definition, but **the method body is empty**. Is it really needed?

When I use another Trait which defines `__construct`, I cannot use these two Traits together without `insteadof`in Traits use declaration.

Expected usage:

```php

/**
 * @ORM\Mapping\Entity(repositoryClass="CategoryRepository")
 */
class Category
{
	use MagicAccessors;
	use UuidBinary;
}
```

Current usage:

Expected usage:

```php

/**
 * @ORM\Mapping\Entity(repositoryClass="CategoryRepository")
 */
class Category
{
	use MagicAccessors;
	use UuidBinary {
		UuidBinary::__construct insteadof MagicAccessors;
	}
}
```

**Comment by fprochazka** [comment]
Oh, that's a mistake, that shouldn't have been copied from the old object. Goddamit. Removing it is a BC Break :-/

**Comment by hranicka** [comment]
> But removing it is a BC Break

Sorry, but I don't understand. Why is it a BC-break? :astonished: 

(only question for my curiosity)

**Comment by enumag** [comment]
Because you can no longer call `parent::__construct();` in a class which extends a class that uses this trait.

**Comment by hranicka** [comment]
Oh, @enumag , thank you!

**Comment by Majkl578** [comment]
I'd rather consider this a nasty bug. Any class that uses MagicAccessors and had parent with the constructor now ends up having no parent constructor called at all.

**Comment by hranicka** [comment]
Constructors should not be used in Traits at all, right?

It causes problems when constructor is declared in a Class and in a Trait too.
And there are problems with  constructorsconstructorsng/overriding.

Am I right?

**Comment by Majkl578** [comment]
It's not a constructor-specific issue, rather generic one, but yes. Constructors are just the most common pitfall.

**Comment by fprochazka** [comment]
@Majkl578 do you think i should add it to 3.* also? The issue would be nicely visible, as it would scream for every `parent::` call that is calling the missing method and fix is easy...

**Comment by Majkl578** [comment]
Imho that'd be better than hidden constructor overload causing no parent constructors to be called.
It may also be possible to keep it as is & provide mechanism to call parent constructor if exists... But that sounds ugly.

**Comment by Majkl578** [comment]
Imho that'd be better than hidden constructor overload causing no parent constructors to be called.
It may also be possible to keep it as is & provide mechanism to call parent constructor if exists... But that sounds ugly.

**Comment by fprochazka** [comment]
I'd rather have it scream errors that are easily fixable.
