### ISSUE TITLE
Generated proxies cannot be found since upgrade to v3.1.0

### ISSUE THREAD

**Issue by miloshavlicek** [Kdyby/Doctrine#265]
Since upgrade v3.0.1 to v3.1.0 I face a problem with generated proxies - **only in production mode**. If new proxy should be generated, than debugger reports following error:
Warning: require([...website dir...]/app/../temp/proxies/__CG__[...proxy class name...].php): failed to open stream: No such file or directory

File: ...\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php:209 

207:                switch ($this->autoGenerate) {
208:                    case self::AUTOGENERATE_NEVER:
209:                        require $fileName;
210:                        break;

The file is not generated. When I downgrade to v3.0.1, everything is ok.

**Comment by mrtnzlml** [comment]
Yeah, even though I reported this little BC break to my team, it took ~1 hour and 53 minutes to the first issue reported. You have to use `php index.php orm:generate-proxies` manually. Very nasty. :disappointed:

**Comment by fprochazka** [comment]
What can be also very nasty is when you forgot to delete the old proxies. You should really have a deployment process that generates the proxies for you.

**Comment by fprochazka** [comment]
I'm thinking of reverting this one and postponing it till [v4.0](https://github.com/Kdyby/Doctrine/milestones/v4.0).

**Comment by enumag** [comment]
@fprochazka Please do, it wasn't really intended for 3.x. I need to send one more PR to achieve independence on Kdyby/Events anyway (in 3.1 it is achieveable but ugly).

**Comment by fprochazka** [comment]
Tagged [v3.1.1](https://github.com/Kdyby/Doctrine/releases/tag/v3.1.1) which reverts this.
