### ISSUE TITLE
Why is BaseEntity deprecated

### ISSUE THREAD

**Issue by simPod** [Kdyby/Doctrine#271]
Bonjour,

I'm curious why is BaseEntity deprecated. I couldn't find any info about the deprecation reason and how to use doctrine without BaseEntity.

Thank you!

**Comment by simPod** [comment]
Ok, in case someone was confused like me, use MagicAccessors trait instead

**Comment by fprochazka** [comment]
Even better, to be future proof, use https://github.com/Kdyby/DoctrineMagicAccessors :)
