### ISSUE TITLE
EM binding to debug panel fails after EM reset

### ISSUE THREAD

**Issue by fmasa** [Kdyby/Doctrine#275]
Kdyby/Doctrine removes Entity Manager service from DIC after entity manager reset (via. ManagerRegistry::reset. When I want to use entity manager again, service factory tries to bind new Entity Manager to debug bar which ouputs in:
**Kdyby\Doctrine\InvalidStateException: Doctrine Panel is already bound to entity manager.**

**Comment by vhenzl** [comment]
I have the same problem. It happens after rollback performed by $entityManager->transactional().

**Comment by FilipLukac** [comment]
I have same issue with deployment when running migrations

**Comment by fprochazka** [comment]
That is desired, there should be new instance of the panel for new instance of EntityManager.

**Comment by fprochazka** [comment]
Conclusion: I have to split the panel into at least two panels

* one will render queries
* one will render EM exceptions in panel

**Comment by fprochazka** [comment]
The cache stats panel now shows only data from the last attached EntityManager. Solving this would require spliting the panel even more. This will be solved as part of https://github.com/Kdyby/Doctrine/issues/238#issuecomment-304348927
