### ISSUE TITLE
QueryObject::postFetch is not called in QueryObject::fetchOne

### ISSUE THREAD

**Issue by lku** [Kdyby/Doctrine#276]
Hi, it looks like `QueryObject::postFetch` method is not called if I use `QueryObject::fetchOne` for fetching only one entity, only in `ResultSet::getIterator` method. Is it intentionaly or a bug?

**Comment by jiripudil** [comment]
I'd say it's intentional, `postFetch` is [a way to solve the N+1 problem](https://github.com/Kdyby/Doctrine/blob/master/docs/en/optimizing-query-objects.md#harder-better-faster-stronger), which is not a problem when fetching only one entity :)

**Comment by lku** [comment]
@jiripudil Yeah, but that way I cannot reuse the query object for fetching collection and one entity, right? Or am I missing something?

And of course this: https://github.com/Kdyby/Doctrine/blob/239d21bd58f7f3c675d3264ba165f0da0b01014c/src/Kdyby/Doctrine/QueryObject.php#L177-L180

**Comment by fprochazka** [comment]
I guess it makes sense to call it here also.
