### ISSUE TITLE
"CacheJournal has not been provided"

### ISSUE THREAD

**Issue by radekdostal** [Kdyby/Doctrine#279]
I switched from Kdyby/Doctrine 3.1.1 to 3.1.2 and Nette from 2.3.10 to 2.4.0. Now an Nette\InvalidStateException is thrown with "CacheJournal has not been provided", where `$entityManager->getRepository(MyEntity::class)` is called.

**Comment by matej21** [comment]
You have to enable pdo_sqlite extension (and don't forget do remove a cache after)

**Comment by radekdostal** [comment]
It works! Thx.
