### ISSUE TITLE
Why does NonLockingUniqueInserter ignore nullable relations when building the INSERT query?

### ISSUE THREAD

**Issue by Andrewsville** [Kdyby/Doctrine#288]
Is there a reason to not save a relation when it is set (but is nullable)? Using merge & flush you are letting Doctrine set it via a subsequent UPDATE query but is that really necessary?

TL; DR: Is [this](https://github.com/Kdyby/Doctrine/blob/v3.1.2/src/Kdyby/Doctrine/Tools/NonLockingUniqueInserter.php#L247) necessary (and why)?

**Comment by fprochazka** [comment]
I don't remember why I added it. I guess it can be changed.

**Comment by fprochazka** [comment]
Related #290
