### ISSUE TITLE
kdyby findBy() with OFFSET in kdyby\console fail

### ISSUE THREAD

**Issue by zemnet** [Kdyby/Doctrine#289]
Hi,
I have problem in findBy function in kdyby/console with offset.

Have this configuration....

```php
 $paginator = new Nette\Utils\Paginator;

 $paginator->setItemCount($this->total);

 $paginator->setItemsPerPage(100);

 for($page=1;$page <= $paginator->getLastPage();$page++) {

	$paginator->setPage($page);

	$this->entityManager->findBy($filter, $order, $paginator->getLength(), $paginator->getOffset());

 }
```

If I have 800 items,
on first loop my result is first 100 items,
on 2 loop my result contain third 100 items,
on 3 loop my result contain fifth 100 items,
on 4 loop my result contain sixth 100 items,
on 5-8 loop my result is empty....

Pagination getOffset is correct, but result is reduced.

Over nette presenter, offset work well...

**Comment by fprochazka** [comment]
@zemnet aren't you somehow modyfing the entities in a way that they won't pass the condition? AFAIK Kdyby doesn't modify the behaviour of `findBy` on `EntityManager` and there it's either Doctrine bug, or bug in your code.
