### ISSUE TITLE
Compatibility with Nette

### ISSUE THREAD

**Issue by Zarganwar** [Kdyby/Doctrine#300]
Hi, is it planned to make it compatible with new versions of Nette components? Or exists some workaround to use it on higher nette version. I've tryed 2.4.x-dev and there is problem with 

> Nette\DI\Statement::setEntity is deprecated, change Statement object itself

Current stable version of kdyby/doctrine says  :-(
  Problem 1
    - Conclusion: remove nette/robot-loader v3.0.0
    - Conclusion: don't install nette/robot-loader v3.0.0
    - kdyby/doctrine v3.2.0 requires nette/robot-loader ^2.4@dev -> satisfiable by nette/robot-loader[v2.4.0, v2.4.1, v2.4.2].
    - kdyby/doctrine v3.2.1 requires nette/robot-loader ^2.4@dev -> satisfiable by nette/robot-loader[v2.4.0, v2.4.1, v2.4.2].
    - Can only install one of: nette/robot-loader[v2.4.0, v3.0.0].
    - Can only install one of: nette/robot-loader[v2.4.1, v3.0.0].
    - Can only install one of: nette/robot-loader[v2.4.2, v3.0.0].
    - Installation request for nette/robot-loader (locked at v3.0.0, required as ^2.4 || ^3.0) -> satisfiable by nette/robot-loader[v3.0.0].
    - Installation request for kdyby/doctrine ^3.2 -> satisfiable by kdyby/doctrine[v3.2.0, v3.2.1].

I'am newbie in Doctrine and this is recomended by all Nette users. But :-(

**Comment by Zarganwar** [comment]
It looks good. Is it safe? +/-

**Comment by enumag** [comment]
I would not recommend it on production. For now I would recommend downgrading robot-loader instead.

**Comment by Zarganwar** [comment]
OK, thank you for fast solution. 👍
