### ISSUE TITLE
Undefined index: Doctrine\ORM\Event::onClear on 7.1

### ISSUE THREAD

**Issue by martingold** [Kdyby/Doctrine#303]
Doctrine spits out `Undefined index: Doctrine\ORM\Event::onClear` when using `$dao->find($id)`. It works as usual when the line is suppressed using @.

I created minimal code [repository](https://github.com/martingold/kdyby-doctrine-bug-repro) to reproduce this issue. It's usual nette sandbox.

using php 7.1.6

![selection_002](https://user-images.githubusercontent.com/15158789/29249181-2b143e2a-802b-11e7-9f49-337ced6912c0.png)

**Comment by forgie1** [comment]
Actually this happens from last doctrine upgrade to v2.5.7.

I guess it is because of this solved issue: https://github.com/doctrine/doctrine2/pull/1515

**Comment by martingold** [comment]
You are right, requiring doctrine/orm at version 2.5.5 solves the issue. We need some future-proof solution.

**Comment by petrparolek** [comment]
fixed by https://github.com/doctrine/doctrine2/releases/tag/v2.5.9
