### ISSUE TITLE
It will be support for Nette 3 ?

### ISSUE THREAD

**Issue by misaon** [Kdyby/Doctrine#306]

**Comment by enumag** [comment]
At the moment it seems that [Nettrine](https://github.com/nettrine) might be ready sooner than Kdyby is updated.

**Comment by f3l1x** [comment]
At this moment we're trying to prepare MVP of Nettrine ORM + DBAL. It definitely takes a lot of time to at the same level as Kdyby, but we're not creating clone od Kdyby. I would rather name it as minimal must-havev integration of Doctrine to Nette. Maybe with some extra stuff around.

It would be great to join us a set expectations of the MVP.

**Comment by haltuf** [comment]
I'm going to *TRY* to prepare PR for Nette v3.0 compatibility.
Anyone wishing to help me with this, please contact me.

**Comment by vojta001** [comment]
For those finding this issue: Nette 3.0 compatibility was added in #330 and we are currently waiting for a release.

**Comment by krkabol** [comment]
Hi, is there some progress about the Nette 3.0 compatible release? Or is something that we can help with?

**Comment by enumag** [comment]
@krkabol See this comment for the reason why I didn't tag it yet https://github.com/Kdyby/Doctrine/pull/330#issuecomment-524046640

**Comment by freiondrej** [comment]
@enumag is the kdyby/console dependency a deal breaker? Now that PHP 8 is almost there, nette 3.0 is a must-have, because nette 2.4 is not compatible with PHP 8 (according to https://nette.org/en/maintenance#toc-php-compatibility).

**Comment by enumag** [comment]
At this point I think I have to reconsider. I still dislike the dependency but then again Kdyby is mostly dead by now. It won't hurt to have a Nette 3.0 compatible release for the legacy applications. Although long-term wise you should consider a migration to Contributte and Nettrine.

**Comment by enumag** [comment]
For anyone who wants a release, please send a PR to add PHP 7.4 into `.travis.yml`. If 8.0 is available on travis then I'd recommend adding it as well.

**Comment by enumag** [comment]
Also https://github.com/Kdyby/Doctrine/pull/334 should likely be finished as well. I can't merge it because it's failing though.

**Comment by f3l1x** [comment]
> Although long-term wise you should consider a migration to Contributte and Nettrine.

Thanks @enumag. Contributte/Nettrine has active and growing community, I would also offer my to help to anyone with migration.

**Comment by darkWolf-PR** [comment]
> 
> 
> > Although long-term wise you should consider a migration to Contributte and Nettrine.
> 
> Thanks @enumag. Contributte/Nettrine has active and growing community, I would also offer my to help to anyone with migration.

I´ve tried Nettrine conversion few months ago on small website build with kdyby/doctrine(for who know what reason...) and it was hell of a problem, had to make changes to almost every php file in it. We have larger system running for dozen or more clients with nette 2.3 and kdyby/doctrine and that would make me rewrite hundreds of files, it would take months to get everything working. Months no one would give me for that... 

Not mention many problems with Nettrine documentation and demos running different versions, contradicting each other with configuration etc.

**Comment by enumag** [comment]
I don't have personal experience with Nettrine so I don't know how good their documentation and demos are. However unlike Kdyby it's still very active much more likely to fix bugs and docs.

If your codebase requires that much rewriting from Kdyby to Nettrine then I believe you have a much bigger problem. Your codebase should be dependent on Doctrine but preferably not on a particular Nette integration. So my recommendation is to first refactor your codebase to be less tied to Kdyby (= don't write new features that way and gradually refactor the old ones) and when it's in better state, try migrating to Nettrine again. Btw. are you sure that most of the things to change isn't a simple matter of bulk regex replace in phpstorm?

**Comment by darkWolf-PR** [comment]
Yeah, I know...and no one cares, so I can do pretty much jackshit...no one give me months to rewrite all the crap, whose author is about 3-4? years gone... It´s not tied only to Kdyby/Doctrine, there was a lot of other stuff locking updating. like Grido in backend locking everything on Nette 2.3 and php 7.0 for example. It´s basically a vicious circle between component versions(variants) and php versions that ensures that only way to update/switch is update/switch everything at once, which would take months... It´s not starting version, it was build on something like php 5.2-5.3, I´m pretty sure parts were build with Nette 2.0 beta x. It was already hell of a fight to get everything working on or be compatible with php 7 instead of 5.x as that at least made whole system work a bit faster.

**Comment by f3l1x** [comment]
I am sorry for your codebase :( 

We can ask @TomasVotruba, if there is a way to use rector to migrate from kdyby to contributte + nettrine.

**Comment by TomasVotruba** [comment]
@f3l1x Depends how many people would use it. 
If you can get me the diffs with small code samples, we should be able to add such set.

**Comment by fmasa** [comment]
We are currently migrating one project from Kdyby\Doctrine to Nettrine\Dbal + custom ORM integration as well. For us the biggest pain points are new and tweaked EntityRepository methods for Kdyby. Otherwise it would be easy to do a simple replace.
