### ISSUE TITLE
Problem with doctrine/orm BC breaks

### ISSUE THREAD

**Issue by martinknor** [Kdyby/Doctrine#309]
Because in composer require is "doctrine/orm": "~2.5" it handle new 2.6 version with bc breaks. "doctrine/orm": "~2.5.0" will be better.

https://github.com/doctrine/doctrine2/releases/tag/v2.6.0

![image](https://user-images.githubusercontent.com/2004222/34205839-4a67551e-e584-11e7-9b33-050730d3ca6f.png)

**Comment by martinknor** [comment]
PR: https://github.com/Kdyby/Doctrine/pull/310

**Comment by Majkl578** [comment]
What BC breaks?

**Comment by martinknor** [comment]
Problem is with `\Doctrine\ORM\Tools\Pagination\Paginator::getCountQuery`, because i have parameters in orderBy and it throws **Invalid parameter number: number of bound variables does not match number of tokens**

```php
$datasource->addOrderBy('IF(s.type = :statusDone, null, DATEDIFF(er.dueDate, NOW()))', 'desc');
$datasource->setParameter('statusDone', TaskStatusType::DONE);
```

**Comment by Majkl578** [comment]
Can you debug it further? I.e. the difference between 2.5 and 2.6? Is any parameter lost or is there parameter extra? This doesn't necessarily mean it's ORM bug, it could be bugfix as well and bug on our side.

**Comment by enumag** [comment]
Hmm... was [this](https://github.com/doctrine/doctrine2/pull/6243) a BC break after all?

**Comment by Majkl578** [comment]
I don't see how that PR could be related, it has nothing to do with bound parameters.

**Comment by enumag** [comment]
Probably not, I just remembered fixing something about counting in Paginator which seems to be broken here. It could be some other change of course.

**Comment by martinknor** [comment]
Problem is in `\Doctrine\ORM\Tools\Pagination\Paginator::getIterator`
with this line ` $subQuery->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, LimitSubqueryOutputWalker::class);`
I have sql

```sql
SELECT t0_.name AS name_0, t0_.reference AS reference_1, t0_.description AS description_2, t0_.start_date AS start_date_3, t0_.due_date AS due_date_4, t0_.done_date AS done_date_5, t0_.percent AS percent_6, t0_.private AS private_7, t0_.id AS id_8, t0_.materialized_path AS materialized_path_9, t0_.created_at AS created_at_10, t0_.updated_at AS updated_at_11, t0_.deleted_at AS deleted_at_12, t0_.creator_id AS creator_id_13, t0_.owner_id AS owner_id_14, t0_.proposer_id AS proposer_id_15, t0_.structure_id AS structure_id_16, t0_.type_id AS type_id_17, t0_.status_id AS status_id_18, t0_.priority_id AS priority_id_19, t0_.meeting_id AS meeting_id_20, t0_.check_list_id AS check_list_id_21 FROM task t0_ INNER JOIN task_status t1_ ON t0_.status_id = t1_.id WHERE t0_.owner_id = ? AND t0_.type_id = ? AND t1_.type <> ? AND t0_.deleted_at IS NULL ORDER BY IF(t1_.type = ?, ?, DATEDIFF(t0_.due_date, NOW())) ASC LIMIT 10 OFFSET 0
```

and after this walker

```sqk
SELECT DISTINCT id_8 FROM (SELECT DISTINCT id_8, IF(type_13 = ?, ?, DATEDIFF(due_date_4, NOW())) FROM (SELECT t0_.name AS name_0, t0_.reference AS reference_1, t0_.description AS description_2, t0_.start_date AS start_date_3, t0_.due_date AS due_date_4, t0_.done_date AS done_date_5, t0_.percent AS percent_6, t0_.private AS private_7, t0_.id AS id_8, t0_.materialized_path AS materialized_path_9, t0_.created_at AS created_at_10, t0_.updated_at AS updated_at_11, t0_.deleted_at AS deleted_at_12, t1_.type AS type_13, t0_.creator_id AS creator_id_14, t0_.owner_id AS owner_id_15, t0_.proposer_id AS proposer_id_16, t0_.structure_id AS structure_id_17, t0_.type_id AS type_id_18, t0_.status_id AS status_id_19, t0_.priority_id AS priority_id_20, t0_.meeting_id AS meeting_id_21, t0_.check_list_id AS check_list_id_22, t1_.view_sugar_id AS view_sugar_id_23 FROM task t0_ INNER JOIN task_status t1_ ON t0_.status_id = t1_.id WHERE t0_.owner_id = ? AND t0_.type_id = ? AND t1_.type <> ? AND t0_.deleted_at IS NULL) dctrn_result_inner ORDER BY IF(type_13 = ?, ?, DATEDIFF(due_date_4, NOW())) ASC) dctrn_result LIMIT 10 OFFSET 0
```

So i think the problem is duplicate of ? as parameter

**Comment by Majkl578** [comment]
Please [report it upstream](https://github.com/doctrine/doctrine2/issues/new), attach a test case if possible.
