### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by JohnyRicio** [Kdyby/Doctrine#313]
Please fix support for PHP 7.2

Never user Nette\Object. Instead them use Nette\SmartObject
- class Panel extends Nette\Object implements IBarPanel, Doctrine\DBAL\Logging\SQLLogger
- class RepositoryFactory  extends Nette\Object implements Doctrine\ORM\Repository\RepositoryFactory
- class CacheCleaner extends Nette\Object
- class EntityListenerResolver extends Nette\Object implements \Doctrine\ORM\Mapping\EntityListenerResolver
- class ProxyAutoloader extends Nette\Object
- class SimpleParameterFormatter extends Nette\Object
- class DqlSelection extends Nette\Object implements \IteratorAggregate
- atc...

**Comment by enumag** [comment]
Known, partially solved in #307, the rest should be solved in #311.
