### ISSUE TITLE
Is it possible to add 'like' clause in findBy method?

### ISSUE THREAD

**Issue by Jigsik** [Kdyby/Doctrine#324]
It is really cool, that EntityRepository includes options like >, <, >=, .., but I am really sad, because option 'like' is missing. Is it possible to add this option to findBy method? Thanks.

**Comment by janatjak** [comment]
Try create PR https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/QueryBuilder.php#L46

**Comment by Jigsik** [comment]
Works like a charm! Thanks 👍

**Comment by enumag** [comment]
send a PR ;-)
